#!/bin/sh
HOSTIP="10.128.128.1"
NETMASK="255.255.255.0"
DHCP_START="10.128.128.50"
DHCP_END="10.128.128.150"
IFNAME=`sudo tunctl -b -u $USER`

sudo ifconfig $IFNAME $HOSTIP netmask $NETMASK up
sudo dnsmasq --listen-address=$HOSTIP -z --dhcp-range=$DHCP_START,$DHCP_END,12h
vde_switch -sock /tmp/vde_switch0 -tap $IFNAME -daemon