#!/bin/bash
#set -x
dir=$(dirname $0)

if [[ -z $SESA_BASEDIR && $dir/../../EbbRT ]]; then
   export KHCTL_BASEDIR=$(readlink -f ${dir}/../../sesadb)
else
   export KHCTL_BASEDIR=${SESA_BASEDIR:-~/sesa/sesadb }
fi

if [[ $(type -p khctl ) ]]; then

   declare SESA_UTIL=khctl
fi

if [[ -z $SESA_UTIL && $dir/../../EbbRT ]]; then
   declare SESA_UTIL=$(readlink -f ${dir}/../../scripts/khctl)
else
   declare SESA_UTIL=${SESA_UTIL:-~/sesa/scripts/khctl}
fi

if [[ ! $(type -p $SESA_EMUCMD ) ]]; then
   export SESA_EMUCMD=qemu-system-x86_64
fi
export SESA=1

$SESA_UTIL SESAcleanAll

