#!/bin/bash
# Clean database, remove all applications / networks 

if [[ ! -d $KHCTL_BASEDIR ]]; then
  echo "ERROR: $KHCTL_BASEDIR not found"
  exit 1
fi

if [[ $(type -p khctl ) ]]; then

   declare SESA_UTIL=khctl
fi

$SESA_UTIL SESAcleanAll
