#!/bin/bash
# setup a build tree conducive to sesa/kittyhawk utility layer usage 
# 
# Instructions: The setup the EbbRT x84_64 utility build run this script from
# the desires build direction, passing in the EbbRT source directory as the
# only argument.
src=$1
imgtype=iso

# By default we assume the script is run from EbbRt/../build
if [[ -z $src ]]
then
    src=../EbbRT
fi

# check if we've discovered the EbbRT source
if [[ ! -a $src/configure.ac ]]; then
  echo "ERROR: $src does not seem to be a known src directory"
  exit -1
fi

echo "Source directory found: $src"
echo "Running autoconfig..."

autoreconf -i $src
if [[ ! -a $src/configure ]]
then
  echo "ERROR: $src/configure not found"
  exit -1
fi

base=.
ulnx=$base/ulnx
bare=$base/bare
#TODO: debug flags & optimisations
flags='-g -O0'

# Run configuration and make for both platforms
mkdir -p $bare $ulnx

echo "$src/configure 'CXXFLAGS=$flags' " >> $ulnx/doconfig
(cd $ulnx; . doconfig && make)

echo "$src/configure 'CXXFLAGS=$flags' --host=x86_64-pc-ebbrt " >> $bare/doconfig
(cd $bare; . doconfig && make)

#################################################
# envoirnment variables
#################################################
cat > $base/loadenv << EOF
export SESA=1
export SESA_SRC=$src
export KHCTL_BASEDIR=$(readlink -f ${base}/khdb)
EOF
echo 'export PATH=$PATH:$SESA_SRC/util/kh' >> $base/loadenv

#################################################
# makefile
#################################################

cat > $base/Makefile << EOF
all: .DEFAULT
.DEFAULT:
	make -C ulnx \${MAKECMDGOALS}
	make -C bare \${MAKECMDGOALS}
EOF

#################################################
# make the apps
#################################################

touch $base/makeapp
chmod 755 $base/makeapp

cat > $base/makeapp << EOF
#!/bin/bash
set -x
base=$base
ulnx=$ulnx
bare=$bare
imgtype=$imgtype
EOF

echo 'app=$1
if [[ -z $app ]]
then
  echo "ERROR: include application name"
  exit -1
fi

echo " building linux app"
make -C $ulnx src/app/$app/$app
echo " building baremetal app"
make -C $bare src/app/$app/$app.$imgtype
  
'>> $base/makeapp 


#################################################
# run the apps
#################################################

touch $base/runapp
chmod 755 $base/runapp

cat > $base/runapp << EOF
#!/bin/bash
src=$src
base=$base
ulnx=$ulnx
bare=$bare
imgtype=$imgtype
export SESA_GET=khget
EOF

echo '
app=$1
option=$2
if [[ -n $3 ]]; then count=$3; else count=1; fi
if [[ -n $4 ]]; then 
    if [[ $UID != 0 ]]; then
      echo "Error: sudo required for TAP interfaces"
      exit 1
    else
      export SESA_TAP=$4
    fi
fi

if [[ -z $app  || ! ($option > 0) ]]
then
  echo "USAGE: $0 <appName> <runType> [bareCount] [tap] " 
  echo "     appName  : application/boot img to run"
  echo "     runType  : execution arrangement"
  echo "                  1)  baremetal-only (qemu)"
  echo "                  2)  front-end process, many baremetal (qemu)"
echo "                  3)  linux front-end. Treats appName as boot image (qemu)" 
  echo "   bareCount  : number of backend nodes, default is 1" 
  echo "         tap  : tap interface (sudo required)" 
  exit 1;
fi

APPNAME="$app$RANDOM"
BARE_IMG=$(readlink -f ${base}/bare/src/app/$app/$app.$imgtype)
FNT_IMG=$(readlink -f ${base}/ulnx/src/app/$app/$app)

case $option in
    1)
    bkcmd="$($SESA_GET $APPNAME $BARE_IMG $count)"
    echo $bkcmd
    ;;
    ########################
    2)
    xterm -hold -e $FNT_IMG &
    sleep 5
    bkcmd="$($SESA_GET $APPNAME $BARE_IMG $count)"
    ;;
    ########################
    3)
    if [[ ! (-a $app) ]]; then
      echo "Error: boot image not found $app"
      exit 1
    fi
    ftcmd="$($SESA_GET -m $base -i "linux"$RANDOM $app )" 
    serials=$(echo "$ftcmd" | grep serial | while read node nn junk path; do echo $path; done)
    for sock in $serials; do
      xterm -e socat - UNIX-CONNECT:$sock &
    done
    exit
    ;;
    ########################
    *) echo "Error: invalid execution choice";;
esac
' >> $base/runapp 
