#!/bin/bash
# setup a build tree conducive to sesa/kittyhawk utility layer usage 
 
# Info: The setup of an EbbRT x84_64 utility build envoirnment + helper
# scripts

# Instructions: run this script from the desiref build direction, 
# passing in the EbbRT source directory as the first argument.
# e.g., 
# mkdir ~/build; cd ~/build; 
# ~/EbbRT/util/setup ~/EbbRT/
#

#################################################
# setup new build location
#################################################

src=$1
imgtype=iso

# By default we assume the script is run from EbbRt/../build
if [[ -z $src ]]
then
  echo "ERROR: pass in path to source directory as first argument"
  exit -1
fi

# check if we've discovered the EbbRT source
if [[ ! -a $src/configure.ac ]]; then
  echo "ERROR: $src does not seem to be a known src directory"
  exit -1
fi

echo "Source directory found: $src"
echo "Running autoconfig..."

autoreconf -i $src
if [[ ! -a $src/configure ]]
then
  echo "ERROR: $src/configure not found"
  exit -1
fi

base=.
ulnx=$base/ulnx
bare=$base/bare
scripts=$base/scripts
khscripts=$src/util/kh/khscripts
#TODO: variable debug flags & optimisations
flags='-g -O0'
#TODO: variable boot images 
bootimg=sesalnx

# Run configuration and make for bare,ulnx platforms
mkdir -p $bare $ulnx $scripts
echo "$src/configure 'CXXFLAGS=$flags' " >> $ulnx/doconfig
(cd $ulnx; . doconfig && make)
echo "$src/configure 'CXXFLAGS=$flags' --host=x86_64-pc-ebbrt " >> $bare/doconfig
(cd $bare; . doconfig && make)

cat > $base/Makefile << EOF
all: .DEFAULT
.DEFAULT:
	make -C ulnx \${MAKECMDGOALS}
	make -C bare \${MAKECMDGOALS}
EOF


#################################################
# environment variables into a file
#################################################
cat > $base/enviro<< EOF
export SESA=1
export SESA_SRC=$src
export KHCTL_BASEDIR=$(readlink -f ${base}/khdb)
EOF
echo 'export PATH=$PATH:$SESA_SRC/util/kh' >> $base/enviro


#################################################
# quick make script
#################################################

touch $base/makeapp
chmod 755 $base/makeapp

cat > $base/makeapp << EOF
#!/bin/bash
base=$base
ulnx=$ulnx
bare=$bare
imgtype=$imgtype
EOF
cat $khscripts/makeapp-base >> $base/makeapp 

#################################################
# quick run script
#################################################

touch $base/runapp
chmod 755 $base/runapp

cat > $base/runapp << EOF
#!/bin/bash
src=$src
base=$base
ulnx=$ulnx
bare=$bare
imgtype=$imgtype
export SESA_GET=khget
##### LINUX IMAGE #######################################
sesalnx=$HOME/sesalnx.img
config_dir=/mnt/app
share_dir=/mnt/share
#########################################################
EOF
cat $khscripts/runapp-base >> $base/runapp 

#################################################
# copy misc scripts
#################################################
cp $khscripts/$bootimg/* $scripts

####
echo "Setup complete"
